ViewComponents/Models/Person.cs
namespace ViewComponentsDemo.Models
{
    public class Person
    {
        public string? PersonName { get; set; }
        public string? JobTitle { get; set; }
    }
}

ViewComponents/Models/PersonGridModel.cs
namespace ViewComponentsDemo.Models
{
    public class PersonGridModel
    {
        public string GridTitle { get; set; } = string.Empty;

        public List<Person> Persons { get; set; } = new List<Person>();
    }
}

ViewComponents/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace PartialViews.Controllers
{
    public class HomeController : Controller
    {
        [Route("/")]
        public IActionResult Index()
        {
            return View();
        }
        [Route("about")]
        public IActionResult About()
        {
            return View();
        }
    }
}

ViewComponents/ViewComponents/GridViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ViewComponentsDemo.Models;

namespace ViewComponentsDemo.ViewComponents
{
    //[ViewComponent]
    public class GridViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(PersonGridModel grid) {

            PersonGridModel personModel = new PersonGridModel()
            {
                GridTitle = "Persons List",
                Persons = new List<Person>() {
                    new Person() {PersonName = "John", JobTitle="Manager"},
                    new Person() {PersonName = "Jones", JobTitle="Architect"}
                }
            };
            //ViewData["Grid"] = personModel;

            return View("Sample", grid);
            //try to invoke a partialview Shared/Components/Grid/Default.cshtml
        }
    }
}

ViewComponents/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h1>About</h1>
<p>
    Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
</P>

@{

    PersonGridModel personModel = new PersonGridModel()
    {
        GridTitle = "Persons List",
        Persons = new List<Person>() {
            new Person() {PersonName = "John", JobTitle="Manager"},
            new Person() {PersonName = "Jones", JobTitle="Architect"}
        }
    };
}

@await Component.InvokeAsync("Grid", personModel)


@* @await Component.InvokeAsync("Grid") *@


@{

    PersonGridModel personModel2 = new PersonGridModel()
    {
        GridTitle = "Persons List",
        Persons = new List<Person>() {
            new Person() {PersonName = "Miller", JobTitle="Manager"},
            new Person() {PersonName = "Himler", JobTitle="Architect"}
        }
    };
}

<vc:grid  grid="personModel2"></vc:grid> 

ViewComponents/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}
<h1>HOME</h1>
<button class="button button-blue-back" id="load-employees-button">Load</button>
<script src="Script.js" ></script>

@* Call ViewComponent *@

@{
    PersonGridModel personModel = new PersonGridModel()
    {
        GridTitle = "Employees List",
        Persons = new List<Person>() {
            new Person() {PersonName = "James", JobTitle="Associte"},
            new Person() {PersonName = "Billy", JobTitle="Sales Manager"}
        }
    };
}

@await Component.InvokeAsync("Grid", new {
    grid = personModel
})

ViewComponents/Views/Shared/Components/Grid/Sample.cshtml
@model PersonGridModel

<div class="box">
    <h3>@Model.GridTitle</h3>
    <table class="table w-100">
        <thead>
            <th>
                Sl No
            </th>
            <th>
                Name
            </th>
        </thead>
        <tbody>
            @foreach(Person person in Model.Persons)
            {
                <tr>
                    <td>@person.PersonName</td>
                    <td>@person.JobTitle</td>
                </tr>
            }
        </tbody>
    </table>
</div>

ViewComponents/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <link href="~/StyleSheet.css" rel="stylesheet"/>
</head>
<body style="font-family:Arial">
    <div class="container">
        <div class="navbar">
            <div class="navbar-brand">AspNet Core App</div>
            <ul>
                <li><a href="~/">Home</a></li>
                <li><a href="~/about">About</a></li>
            </ul>
        </div>
        <div class="page-content">
            @RenderBody()
        </div>
    </div>
    
</body>
</html>